
async function main() {

  try {
    console.log('try ...')
  } catch (error) {
    console.error(error)
  }

}

main()